const WORD_LISTS = {
    4: ['ABLE', 'ALSO', 'AREA', 'BACK', 'BALL', 'BANK', 'BASE', 'BEAR', 'BEAT', 'BEEN',
        'BEST', 'BIRD', 'BLUE', 'BOAT', 'BODY', 'BOOK', 'BORN', 'BOTH', 'BUSY', 'CALL',
        'CAME', 'CARE', 'CASE', 'CELL', 'CITY', 'CLUB', 'COLD', 'COME', 'COST', 'DARK',
        'DATA', 'DEAL', 'DEEP', 'DOOR', 'DOWN', 'DRAW', 'DROP', 'EACH', 'EASY', 'EDGE',
        'EVEN', 'EVER', 'FACE', 'FACT', 'FAIL', 'FALL', 'FAST', 'FEAR', 'FEEL', 'FEET',
        'FILL', 'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM', 'FISH', 'FIVE', 'FLAT', 'FLOW',
        'FOOD', 'FOOT', 'FORM', 'FOUR', 'FREE', 'FROM', 'FULL', 'FUND', 'GAME', 'GAVE',
        'GIRL', 'GIVE', 'GOAL', 'GOES', 'GOLD', 'GONE', 'GOOD', 'GREW', 'GROW', 'HALF',
        'HALL', 'HAND', 'HARD', 'HAVE', 'HEAD', 'HEAR', 'HEAT', 'HELD', 'HELP', 'HERE',
        'HIGH', 'HOLD', 'HOME', 'HOPE', 'HOUR', 'HUGE', 'IDEA', 'INTO', 'ITEM', 'JOIN',
        'JUST', 'KEEP', 'KEPT', 'KIND', 'KING', 'KNEW', 'KNOW', 'LAND', 'LAST', 'LATE',
        'LEAD', 'LEFT', 'LESS', 'LIFE', 'LIKE', 'LINE', 'LIST', 'LIVE', 'LONG', 'LOOK',
        'LOSE', 'LOSS', 'LOST', 'LOVE', 'MAIN', 'MAKE', 'MANY', 'MARK', 'MEAN', 'MEET',
        'MIND', 'MISS', 'MORE', 'MOST', 'MOVE', 'MUCH', 'MUST', 'NAME', 'NEAR', 'NEED',
        'NEXT', 'NICE', 'OPEN', 'OVER', 'PAGE', 'PAIN', 'PAIR', 'PARK', 'PART', 'PASS',
        'PAST', 'PATH', 'PICK', 'PLAN', 'PLAY', 'POOR', 'PULL', 'PUSH', 'RACE', 'RATE',
        'READ', 'REAL', 'REST', 'RISE', 'RISK', 'ROAD', 'ROCK', 'ROLE', 'ROOM', 'RULE',
        'SAFE', 'SAID', 'SALE', 'SAME', 'SAVE', 'SEAT', 'SEEM', 'SELF', 'SELL', 'SEND',
        'SENT', 'SHOT', 'SHOW', 'SIDE', 'SIGN', 'SITE', 'SIZE', 'SKIN', 'SOME', 'SONG',
        'SOON', 'SORT', 'STAR', 'STAY', 'STEP', 'STOP', 'SUCH', 'SURE', 'TAKE', 'TALK',
        'TASK', 'TEAM', 'TELL', 'TERM', 'TEST', 'THAN', 'THAT', 'THEM', 'THEN', 'THEY',
        'THIS', 'TIME', 'TOWN', 'TREE', 'TRUE', 'TURN', 'TYPE', 'UNIT', 'UPON', 'USED',
        'USER', 'VERY', 'VIEW', 'VOTE', 'WAIT', 'WALK', 'WALL', 'WANT', 'WARM', 'WAVE',
        'WAYS', 'WEAR', 'WEEK', 'WELL', 'WENT', 'WERE', 'WEST', 'WHAT', 'WHEN', 'WIDE',
        'WILL', 'WIND', 'WISH', 'WITH', 'WORD', 'WORK', 'YARD', 'YEAH', 'YEAR'],

    5: [
        'ABACK', 'ABATE', 'ABBEY', 'ABIDE', 'ABODE', 'ABOUT', 'ABOVE', 'ABUSE', 'ABYSS', 'ACHED',
        'ACORN', 'ACRID', 'ACTOR', 'ACUTE', 'ADAGE', 'ADAPT', 'ADDED', 'ADEPT', 'ADMIN', 'ADMIT',
        'ADOBE', 'ADOPT', 'ADORE', 'ADORN', 'ADULT', 'AFTER', 'AGAIN', 'AGATE', 'AGAVE', 'AGENT',
        'AGILE', 'AGING', 'AGLOW', 'AGONY', 'AGREE', 'AHEAD', 'AISLE', 'ALARM', 'ALBUM', 'ALERT',
        'ALIBI', 'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLAY', 'ALLEY', 'ALLOT', 'ALLOW', 'ALLOY',
        'ALOFT', 'ALONE', 'ALONG', 'ALOOF', 'ALOUD', 'ALPHA', 'ALTAR', 'ALTER', 'AMBER', 'AMEND',
        'AMISS', 'AMONG', 'AMPLE', 'AMPLY', 'AMUSE', 'ANGEL', 'ANGER', 'ANGLE', 'ANGRY', 'ANGST',
        'ANIME', 'ANNEX', 'ANNOY', 'ANTIC', 'ANVIL', 'AORTA', 'APART', 'APHID', 'APPLE', 'APPLY',
        'APRON', 'APTLY', 'ARBOR', 'ARDOR', 'ARENA', 'ARGUE', 'ARISE', 'ARMOR', 'AROMA', 'AROSE',
        'ARRAY', 'ARROW', 'ARSON', 'ARTSY', 'ASCOT', 'ASHEN', 'ASIDE', 'ASKEW', 'ASSET', 'ATLAS',
        'ATONE', 'ATTIC', 'AUDIO', 'AUDIT', 'AUGUR', 'AUNTY', 'AVAIL', 'AVERT', 'AVIAN', 'AVOID',
        'AWAIT', 'AWAKE', 'AWARD', 'AWARE', 'AWASH', 'AWFUL', 'AWOKE', 'AXIOM', 'AXION', 'AZURE',
        'BACON', 'BADGE', 'BADLY', 'BAGEL', 'BAKER', 'BALMY', 'BANAL', 'BANJO', 'BARGE', 'BARON',
        'BASAL', 'BASED', 'BASES', 'BASIC', 'BASIL', 'BASIN', 'BASIS', 'BATCH', 'BATHE', 'BATON',
        'BATTY', 'BAYOU', 'BEACH', 'BEARD', 'BEAST', 'BEATS', 'BEGAN', 'BEGIN', 'BEING', 'BELCH',
        'BELIE', 'BELLE', 'BELLY', 'BELOW', 'BENCH', 'BENDS', 'BERRY', 'BERTH', 'BESET', 'BETEL',
        'BEVEL', 'BEZEL', 'BIBLE', 'BIDDY', 'BIGHT', 'BIGOT', 'BIJOU', 'BILGE', 'BILLY', 'BINGE',
        'BINGO', 'BIOME', 'BIRCH', 'BIRTH', 'BISON', 'BITTY', 'BLACK', 'BLADE', 'BLAME', 'BLAND',
        'BLANK', 'BLARE', 'BLAST', 'BLAZE', 'BLEAK', 'BLEAT', 'BLEED', 'BLEEP', 'BLEND', 'BLESS',
        'BLIMP', 'BLIND', 'BLINK', 'BLISS', 'BLITZ', 'BLOAT', 'BLOCK', 'BLOKE', 'BLOND', 'BLOOD',
        'BLOOM', 'BLOWN', 'BLUER', 'BLUES', 'BLUFF', 'BLUNT', 'BLURB', 'BLURT', 'BLUSH', 'BOARD',
        'BOAST', 'BOBBY', 'BOGEY', 'BOGUS', 'BOILS', 'BONEY', 'BONUS', 'BOOBY', 'BOOST', 'BOOTH',
        'BOOTY', 'BOOZE', 'BOOZY', 'BORAX', 'BORNE', 'BOSOM', 'BOSSY', 'BOTCH', 'BOUND', 'BOWED',
        'BOWEL', 'BOXER', 'BRACE', 'BRAID', 'BRAIN', 'BRAKE', 'BRAND', 'BRASH', 'BRASS', 'BRAVE',
        'BRAVO', 'BRAWL', 'BRAWN', 'BREAD', 'BREAK', 'BREED', 'BRIAR', 'BRIBE', 'BRICK', 'BRIDE',
        'BRIEF', 'BRINE', 'BRING', 'BRINK', 'BRINY', 'BRISK', 'BROAD', 'BROIL', 'BROKE', 'BROOD',
        'BROOK', 'BROOM', 'BROTH', 'BROWN', 'BRUNT', 'BRUSH', 'BRUTE', 'BUDDY', 'BUDGE', 'BUGGY',
        'BUGLE', 'BUILD', 'BUILT', 'BULGE', 'BULKY', 'BULLY', 'BUMPY', 'BUNCH', 'BUNNY', 'BURLY',
        'BURNT', 'BURST', 'BUSED', 'BUSHY', 'BUTTE', 'BUXOM', 'BUYER', 'BYLAW', 'CABAL', 'CABBY',
        'CABIN', 'CABLE', 'CACAO', 'CACHE', 'CACTI', 'CADDY', 'CADET', 'CALIF', 'CAMEO', 'CANAL',
        'CANDY', 'CANNY', 'CANOE', 'CANON', 'CAPER', 'CAPUT', 'CARAT', 'CARGO', 'CAROL', 'CARRY',
        'CARVE', 'CASTE', 'CATCH', 'CATER', 'CATTY', 'CAULK', 'CAUSE', 'CAVIL', 'CEASE', 'CEDAR',
        'CHAFE', 'CHAFF', 'CHAIN', 'CHAIR', 'CHALK', 'CHAMP', 'CHANT', 'CHAOS', 'CHARD', 'CHARM',
        'CHART', 'CHASE', 'CHASM', 'CHEAP', 'CHEAT', 'CHECK', 'CHEEK', 'CHEER', 'CHESS', 'CHEST',
        'CHICK', 'CHIDE', 'CHIEF', 'CHILD', 'CHILI', 'CHILL', 'CHIME', 'CHIMP', 'CHINA', 'CHIRP',
        'CHOCK', 'CHOIR', 'CHOKE', 'CHORD', 'CHORE', 'CHOSE', 'CHUCK', 'CHUMP', 'CHUNK', 'CHURN',
        'CHUTE', 'CIDER', 'CIGAR', 'CINCH', 'CIRCA', 'CIVIC', 'CIVIL', 'CLAIM', 'CLAMP', 'CLANG',
        'CLANK', 'CLASH', 'CLASP', 'CLASS', 'CLEAN', 'CLEAR', 'CLEAT', 'CLEFT', 'CLERK', 'CLICK',
        'CLIFF', 'CLIMB', 'CLING', 'CLOAK', 'CLOCK', 'CLONE', 'CLOSE', 'CLOTH', 'CLOUD', 'CLOUT',
        'CLOVE', 'CLOWN', 'CLUCK', 'CLUED', 'CLUMP', 'CLUNG', 'COACH', 'COAST', 'COBRA', 'COCOA',
        'COLON', 'COLOR', 'COMET', 'COMFY', 'COMIC', 'COMMA', 'CONCH', 'CONDO', 'CONIC', 'CORAL',
        'CORNY', 'COUCH', 'COUGH', 'COULD', 'COUNT', 'COUPE', 'COURT', 'COVEN', 'COVER', 'COVET',
        'COVEY', 'COWER', 'COYLY', 'CRACK', 'CRAFT', 'CRAMP', 'CRANE', 'CRANK', 'CRASH', 'CRASS',
        'CRATE', 'CRAVE', 'CRAWL', 'CRAZE', 'CRAZY', 'CREAK', 'CREAM', 'CREDO', 'CREED', 'CREEK',
        'CREEP', 'CREME', 'CREPE', 'CREPT', 'CRESS', 'CREST', 'CRICK', 'CRIED', 'CRIER', 'CRIME',
        'CRIMP', 'CRISP', 'CROAK', 'CROCK', 'CRONE', 'CRONY', 'CROOK', 'CROSS', 'CROUP', 'CROWD',
        'CROWN', 'CRUDE', 'CRUEL', 'CRUMB', 'CRUSH', 'CRUST', 'CRYPT', 'CUBIC', 'CUMIN', 'CUPID',
        'CURED', 'CURLY', 'CURRY', 'CURSE', 'CURVE', 'CURVY', 'CUSHY', 'CUTIE', 'CYCLE', 'CYNIC',
        'DAISY', 'DAILY', 'DAIRY', 'DALLY', 'DANCE', 'DANDY', 'DATUM', 'DAUNT', 'DEALT', 'DEATH',
        'DEBAR', 'DEBIT', 'DEBUG', 'DEBUT', 'DECAF', 'DECAY', 'DECOR', 'DECOY', 'DECRY', 'DEFER',
        'DEIGN', 'DEITY', 'DELAY', 'DELTA', 'DELVE', 'DEMON', 'DEMUR', 'DENIM', 'DENSE', 'DEPOT',
        'DEPTH', 'DERBY', 'DETER', 'DETOX', 'DEUCE', 'DEVIL', 'DIARY', 'DICEY', 'DIGIT', 'DILLY',
        'DIMLY', 'DINER', 'DINGO', 'DINGY', 'DIODE', 'DIRGE', 'DIRTY', 'DISCO', 'DITCH', 'DITTO',
        'DITTY', 'DIVER', 'DIZZY', 'DODGE', 'DODGY', 'DOGMA', 'DOING', 'DOLLY', 'DONOR', 'DONUT',
        'DOPEY', 'DOUBT', 'DOUGH', 'DOWDY', 'DOWEL', 'DOWNS', 'DOWNY', 'DOWRY', 'DOZEN', 'DRAFT',
        'DRAIN', 'DRAKE', 'DRAMA', 'DRANK', 'DRAPE', 'DRAWL', 'DRAWN', 'DREAD', 'DREAM', 'DREAR',
        'DREGS', 'DRESS', 'DRIED', 'DRIER', 'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROIT', 'DROLL',
        'DRONE', 'DROOL', 'DROOP', 'DROSS', 'DROVE', 'DROWN', 'DRUID', 'DRUNK', 'DRYER', 'DRYLY',
        'DUCHY', 'DULLY', 'DUMMY', 'DUMPY', 'DUNCE', 'DUSKY', 'DUSTY', 'DUTCH', 'DUVET', 'DWARF',
        'DWELL', 'DWELT', 'DYING', 'EAGER', 'EAGLE', 'EARLY', 'EARTH', 'EASEL', 'EATEN', 'EATER',
        'EBONY', 'EBOOK', 'ECLAT', 'EDICT', 'EDIFY', 'EERIE', 'EGRET', 'EIGHT', 'EJECT', 'EKING',
        'ELATE', 'ELBOW', 'ELDER', 'ELECT', 'ELEGY', 'ELFIN', 'ELIDE', 'ELITE', 'ELOPE', 'ELUDE',
        'ELVES', 'EMAIL', 'EMBED', 'EMBER', 'EMCEE', 'EMERY', 'EMOJI', 'EMOTE', 'EMPTY', 'ENACT',
        'ENDOW', 'ENEMA', 'ENEMY', 'ENJOY', 'ENNUI', 'ENSUE', 'ENTER', 'ENTRY', 'ENVOY', 'EPOXY',
        'EQUAL', 'EQUIP', 'ERASE', 'ERECT', 'ERODE', 'ERROR', 'ERUPT', 'ESSAY', 'ESTER', 'ETHER',
        'ETHIC', 'ETHOS', 'EVADE', 'EVENT', 'EVERY', 'EVICT', 'EVOKE', 'EXACT', 'EXALT', 'EXCEL',
        'EXERT', 'EXILE', 'EXIST', 'EXPAT', 'EXPEL', 'EXTOL', 'EXTRA', 'EXULT', 'EYING', 'FABLE',
        'FACET', 'FAINT', 'FAIRY', 'FAITH', 'FAKER', 'FALSE', 'FANCY', 'FANGS', 'FANNY', 'FARCE',
        'FATAL', 'FATTY', 'FAULT', 'FAUNA', 'FAVOR', 'FEAST', 'FECAL', 'FEIGN', 'FELON', 'FEMME',
        'FEMUR', 'FENCE', 'FERAL', 'FERRY', 'FETAL', 'FETCH', 'FETID', 'FETUS', 'FEVER', 'FEWER',
        'FIBER', 'FIBRE', 'FICUS', 'FIELD', 'FIEND', 'FIERY', 'FIFTH', 'FIFTY', 'FIGHT', 'FILCH',
        'FILET', 'FILLY', 'FILMY', 'FILTH', 'FINAL', 'FINCH', 'FINER', 'FIRST', 'FISHY', 'FIXER',
        'FIXED', 'FIZZY', 'FJORD', 'FLACK', 'FLAIL', 'FLAIR', 'FLAKY', 'FLAME', 'FLANK', 'FLARE',
        'FLASH', 'FLASK', 'FLECK', 'FLEET', 'FLESH', 'FLICK', 'FLIER', 'FLING', 'FLINT', 'FLIRT',
        'FLOAT', 'FLOCK', 'FLOOD', 'FLOOR', 'FLORA', 'FLOSS', 'FLOUR', 'FLOUT', 'FLOWN', 'FLUKE',
        'FLUNG', 'FLUNK', 'FLUSH', 'FLUTE', 'FLYER', 'FOAMY', 'FOCAL', 'FOCUS', 'FOGGY', 'FOIST',
        'FOLLY', 'FORAY', 'FORCE', 'FORGE', 'FORGO', 'FORTE', 'FORTH', 'FORTY', 'FORUM', 'FOUND',
        'FOYER', 'FRAIL', 'FRAME', 'FRANK', 'FRAUD', 'FREAK', 'FREED', 'FRESH', 'FRIAR', 'FRIED',
        'FRILL', 'FRISK', 'FRITZ', 'FROCK', 'FROND', 'FRONT', 'FROST', 'FROTH', 'FROWN', 'FROZE',
        'FRUIT', 'FRYER', 'FUDGE', 'FUGUE', 'FULLY', 'FUNGI', 'FUNKY', 'FUNNY', 'FURRY', 'FUSSY',
        'FUZZY', 'GAFFE', 'GAILY', 'GAMER', 'GAMMA', 'GAMUT', 'GASSY', 'GAUDY', 'GAUGE', 'GAUNT',
        'GAUZE', 'GAVEL', 'GAWKY', 'GAYER', 'GAZER', 'GECKO', 'GEESE', 'GENIE', 'GENRE', 'GHOST',
        'GHOUL', 'GIANT', 'GIDDY', 'GIPSY', 'GIRLY', 'GIRTH', 'GIVEN', 'GIVER', 'GLADE', 'GLAND',
        'GLARE', 'GLASS', 'GLAZE', 'GLEAM', 'GLEAN', 'GLIDE', 'GLINT', 'GLOAT', 'GLOBE', 'GLOOM',
        'GLORY', 'GLOSS', 'GLOVE', 'GLUED', 'GLYPH', 'GNASH', 'GNOME', 'GODLY', 'GOING', 'GOLLY',
        'GONAD', 'GONZO', 'GOOEY', 'GOOFY', 'GOOSE', 'GORGE', 'GOUGE', 'GOURD', 'GRACE', 'GRADE',
        'GRAFT', 'GRAIL', 'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS', 'GRATE',
        'GRAVE', 'GRAVY', 'GRAZE', 'GREAT', 'GREED', 'GREEK', 'GREEN', 'GREET', 'GRIEF', 'GRILL',
        'GRIME', 'GRIMY', 'GRIND', 'GRIPE', 'GROAN', 'GROIN', 'GROOM', 'GROPE', 'GROSS', 'GROUP',
        'GROUT', 'GROVE', 'GROWL', 'GROWN', 'GRUEL', 'GRUFF', 'GRUNT', 'GUANO', 'GUARD', 'GUAVA',
        'GUESS', 'GUEST', 'GUIDE', 'GUILD', 'GUILE', 'GUILT', 'GUISE', 'GULCH', 'GULLY', 'GUMBO',
        'GUMMY', 'GUPPY', 'GUSTO', 'GUSTY', 'GYPSY', 'HABIT', 'HAIRY', 'HALVE', 'HANDY', 'HAPPY',
        'HARDY', 'HAREM', 'HARPY', 'HARRY', 'HARSH', 'HASTE', 'HASTY', 'HATCH', 'HATER', 'HAUNT',
        'HAVEN', 'HAVOC', 'HAZEL', 'HEARD', 'HEART', 'HEATH', 'HEAVE', 'HEAVY', 'HEDGE', 'HEFTY',
        'HEIST', 'HELIX', 'HELLO', 'HENCE', 'HENNA', 'HENRY', 'HERON', 'HILLY', 'HINGE', 'HIPPO',
        'HIPPY', 'HITCH', 'HOARD', 'HOBBY', 'HOIST', 'HOLLY', 'HOMER', 'HONEY', 'HONOR', 'HOOEY',
        'HOOKY', 'HORDE', 'HORNY', 'HORSE', 'HOTEL', 'HOTLY', 'HOUND', 'HOUSE', 'HOVEL', 'HOVER',
        'HOWDY', 'HUMAN', 'HUMID', 'HUMOR', 'HUMPH', 'HUMUS', 'HUNCH', 'HUNKY', 'HURRY', 'HUSKY',
        'HUSSY', 'HYDRA', 'HYENA', 'HYMEN', 'HYPER', 'ICILY', 'ICING', 'IDEAL', 'IDIOM', 'IDIOT',
        'IDLER', 'IDYLL', 'IGLOO', 'ILIAC', 'IMAGE', 'IMBUE', 'IMPEL', 'IMPLY', 'INANE', 'INBOX',
        'INCUR', 'INDEX', 'INEPT', 'INERT', 'INFER', 'INFIX', 'INGOT', 'INLAY', 'INLET', 'INNER',
        'INPUT', 'INTER', 'INTRO', 'IONIC', 'IRATE', 'IRONY', 'ISLET', 'ISSUE', 'ITCHY', 'IVORY',
        'JAUNT', 'JAZZY', 'JEANS', 'JELLY', 'JERKY', 'JETTY', 'JEWEL', 'JIFFY', 'JOINT', 'JOIST',
        'JOKER', 'JOLLY', 'JOUST', 'JUDGE', 'JUICE', 'JUICY', 'JUMBO', 'JUMPY', 'JUNCO', 'JUNKY',
        'JUROR', 'KAPPA', 'KARMA', 'KAYAK', 'KAZOO', 'KEBAB', 'KHAKI', 'KIOSK', 'KITTY', 'KLUTZ',
        'KNACK', 'KNAVE', 'KNEAD', 'KNEED', 'KNEEL', 'KNELT', 'KNIFE', 'KNOCK', 'KNOLL', 'KNOWN',
        'KOALA', 'KRILL', 'LABEL', 'LABOR', 'LADEN', 'LADLE', 'LAGER', 'LANCE', 'LANKY', 'LAPEL',
        'LAPSE', 'LARGE', 'LARVA', 'LASER', 'LASSO', 'LATCH', 'LATER', 'LATHE', 'LATTE', 'LAUGH',
        'LAYER', 'LEACH', 'LEAFY', 'LEAKY', 'LEANT', 'LEAPT', 'LEARN', 'LEASE', 'LEASH', 'LEAST',
        'LEAVE', 'LEDGE', 'LEECH', 'LEERY', 'LEFTY', 'LEGAL', 'LEGGY', 'LEMON', 'LEMUR', 'LEPER',
        'LEVEL', 'LEVER', 'LIBEL', 'LIGHT', 'LIKEN', 'LILAC', 'LIMBO', 'LIMIT', 'LINEN', 'LINER',
        'LINGO', 'LINKS', 'LIPID', 'LITHE', 'LITER', 'LITRE', 'LIVED', 'LIVEN', 'LIVER', 'LIVES',
        'LIVID', 'LLAMA', 'LOAMY', 'LOATH', 'LOBBY', 'LOCAL', 'LOCUS', 'LODGE', 'LOFTY', 'LOGIC',
        'LOGIN', 'LOOPY', 'LOOSE', 'LORRY', 'LOSER', 'LOUSE', 'LOUSY', 'LOVED', 'LOVER', 'LOWER',
        'LOWLY', 'LOYAL', 'LUCID', 'LUCKY', 'LUMEN', 'LUMPY', 'LUNAR', 'LUNCH', 'LUNGE', 'LUPUS',
        'LURCH', 'LURID', 'LUSTY', 'LYING', 'LYMPH', 'LYNCH', 'LYRIC', 'MACRO', 'MADAM', 'MADLY',
        'MAFIA', 'MAGIC', 'MAGMA', 'MAIZE', 'MAJOR', 'MAKER', 'MAMBO', 'MAMMA', 'MAMMY', 'MANGA',
        'MANGE', 'MANGO', 'MANGY', 'MANIA', 'MANIC', 'MANLY', 'MANOR', 'MAPLE', 'MARCH', 'MARRY',
        'MARSH', 'MASON', 'MATCH', 'MATER', 'MATEY', 'MATTE', 'MAUVE', 'MAXIM', 'MAYBE', 'MAYOR',
        'MEALY', 'MEANT', 'MEATY', 'MECCA', 'MEDAL', 'MEDIA', 'MEDIC', 'MELEE', 'MELON', 'MERCY',
        'MERGE', 'MERIT', 'MERRY', 'MESSY', 'METAL', 'METER', 'METRO', 'MICRO', 'MIDGE', 'MIDST',
        'MIGHT', 'MILKY', 'MIMIC', 'MINCE', 'MINER', 'MINIM', 'MINTY', 'MINUS', 'MIRTH', 'MISER',
        'MISSY', 'MITER', 'MITRE', 'MIXED', 'MIXER', 'MOCHA', 'MODAL', 'MODEL', 'MODEM', 'MOGUL',
        'MOIST', 'MOLAR', 'MOLDY', 'MONEY', 'MONTH', 'MOODY', 'MOOSE', 'MORAL', 'MORON', 'MORPH',
        'MOSSY', 'MOTEL', 'MOTIF', 'MOTOR', 'MOTTO', 'MOULD', 'MOULT', 'MOUND', 'MOUNT', 'MOURN',
        'MOUSE', 'MOUSY', 'MOUTH', 'MOVED', 'MOVER', 'MOVIE', 'MOWER', 'MUCKY', 'MUCUS', 'MUDDY',
        'MULCH', 'MUMMY', 'MUNCH', 'MURAL', 'MURKY', 'MUSHY', 'MUSIC', 'MUSKY', 'MUSTY', 'MYRRH',
        'NACHO', 'NADIR', 'NAIVE', 'NAKED', 'NAMED', 'NANNY', 'NASAL', 'NASTY', 'NATAL', 'NAVAL',
        'NAVEL', 'NEEDY', 'NEEDS', 'NEIGH', 'NERDY', 'NERVE', 'NERVY', 'NEVER', 'NEWER', 'NEWLY',
        'NICER', 'NICHE', 'NIECE', 'NIGHT', 'NINJA', 'NINTH', 'NOBLE', 'NOBLY', 'NOISE', 'NOISY',
        'NOMAD', 'NONCE', 'NOOSE', 'NORTH', 'NOSEY', 'NOTCH', 'NOTED', 'NOVEL', 'NUDGE', 'NURSE',
        'NUTTY', 'NYLON', 'NYMPH', 'OAKEN', 'OBESE', 'OCCUR', 'OCEAN', 'OCTAL', 'OCTET', 'ODDER',
        'ODDLY', 'ODOUR', 'OFFAL', 'OFFER', 'OFTEN', 'OGLER', 'OLIVE', 'OLDEN', 'OLDER', 'OMEGA',
        'ONION', 'ONSET', 'OPINE', 'OPIUM', 'OPTIC', 'ORBIT', 'ORDER', 'ORGAN', 'OTHER', 'OTTER',
        'OUGHT', 'OUNCE', 'OUTDO', 'OUTER', 'OUTGO', 'OVARY', 'OVATE', 'OVERT', 'OVINE', 'OVOID',
        'OWING', 'OWNER', 'OXIDE', 'OZONE', 'PADDY', 'PAGAN', 'PAGER', 'PAINT', 'PALSY', 'PANEL',
        'PANIC', 'PANSY', 'PANTS', 'PAPAW', 'PAPER', 'PAPPY', 'PARCH', 'PARRY', 'PARSE', 'PARTY',
        'PASTA', 'PASTE', 'PASTY', 'PATCH', 'PATEN', 'PATER', 'PATIO', 'PATSY', 'PATTY', 'PAUSE',
        'PAYEE', 'PAYER', 'PEACE', 'PEACH', 'PEARL', 'PECAN', 'PEDAL', 'PENAL', 'PENCE', 'PENNE',
        'PENNY', 'PERCH', 'PERIL', 'PERKY', 'PESKY', 'PESTO', 'PETAL', 'PETTY', 'PHASE', 'PHONE',
        'PHONY', 'PHOTO', 'PIANO', 'PICKY', 'PIECE', 'PIETY', 'PIGGY', 'PILOT', 'PINCH', 'PINEY',
        'PINKY', 'PINTO', 'PIPER', 'PIQUE', 'PITCH', 'PITHY', 'PIVOT', 'PIXEL', 'PIXIE', 'PIZZA',
        'PLACE', 'PLAID', 'PLAIN', 'PLAIT', 'PLANE', 'PLANK', 'PLANT', 'PLATE', 'PLAZA', 'PLEAD',
        'PLEAT', 'PLIED', 'PLIER', 'PLONK', 'PLUCK', 'PLUMB', 'PLUME', 'PLUMP', 'PLUNK', 'PLUSH',
        'POESY', 'POINT', 'POISE', 'POKER', 'POLAR', 'POLKA', 'POLYP', 'POOCH', 'POPPY', 'PORCH',
        'POSER', 'POSIT', 'POSSE', 'POUCH', 'POUND', 'POWER', 'PRANK', 'PRAWN', 'PREEN', 'PRESS',
        'PRICE', 'PRICK', 'PRIDE', 'PRIED', 'PRIME', 'PRIMO', 'PRIMP', 'PRINT', 'PRIOR', 'PRISM',
        'PRIVY', 'PRIZE', 'PROBE', 'PRONE', 'PRONG', 'PROOF', 'PROSE', 'PROUD', 'PROVE', 'PROWL',
        'PROXY', 'PRUDE', 'PRUNE', 'PSALM', 'PUBIC', 'PUDGY', 'PUFFY', 'PULPY', 'PULSE', 'PUNCH',
        'PUPIL', 'PUPPY', 'PUREE', 'PURER', 'PURGE', 'PURSE', 'PUSHY', 'PUTTY', 'PYGMY', 'QUACK',
        'QUAFF', 'QUAIL', 'QUAKE', 'QUALM', 'QUART', 'QUASH', 'QUASI', 'QUEEN', 'QUEER', 'QUELL',
        'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUIET', 'QUILL', 'QUILT', 'QUIRK', 'QUITE', 'QUOTA',
        'QUOTE', 'QUOTH', 'RABBI', 'RABID', 'RACER', 'RADAR', 'RADII', 'RADIO', 'RADON', 'RAINY',
        'RAISE', 'RAJAH', 'RALLY', 'RALPH', 'RAMEN', 'RANCH', 'RANDY', 'RANGE', 'RANGY', 'RAPID',
        'RARER', 'RASPY', 'RATIO', 'RATTY', 'RAVEN', 'RAYON', 'RAZOR', 'REACH', 'REACT', 'READY',
        'REALM', 'REARM', 'REBAR', 'REBEL', 'REBUS', 'REBUT', 'RECAP', 'RECUR', 'RECUT', 'REDID',
        'REDLY', 'REEDY', 'REFER', 'REFIT', 'REGAL', 'REHAB', 'REIGN', 'REINS', 'RELAX', 'RELAY',
        'RELIC', 'REMIT', 'REMIX', 'RENAL', 'RENEW', 'REPAY', 'REPEL', 'REPLY', 'RERUN', 'RESET',
        'RESIN', 'RETCH', 'RETRO', 'RETRY', 'REUSE', 'REVEL', 'REVUE', 'RHINO', 'RHYME', 'RIDER',
        'RIDGE', 'RIFLE', 'RIGHT', 'RIGID', 'RIGOR', 'RINSE', 'RIPEN', 'RIPER', 'RISEN', 'RISER',
        'RISKY', 'RIVAL', 'RIVER', 'RIVET', 'ROACH', 'ROAST', 'ROBIN', 'ROBOT', 'ROCKY', 'RODEO',
        'ROGER', 'ROGUE', 'ROOMY', 'ROOST', 'ROPED', 'ROPER', 'ROSIE', 'ROSIN', 'ROTOR', 'ROUGE',
        'ROUGH', 'ROUND', 'ROUSE', 'ROUTE', 'ROVER', 'ROWDY', 'ROWER', 'ROYAL', 'RUDDY', 'RULER',
        'RUMBA', 'RUMOR', 'RUNNY', 'RUNUP', 'RURAL', 'RUSHY', 'RUSTY', 'SABER', 'SABLE', 'SABRE',
        'SAGGY', 'SAINT', 'SALAD', 'SALLY', 'SALON', 'SALSA', 'SALTY', 'SALVE', 'SALVO', 'SANDY',
        'SANER', 'SAPPY', 'SASSY', 'SATAY', 'SATIN', 'SATYR', 'SAUCE', 'SAUCY', 'SAUNA', 'SAUTE',
        'SAVOR', 'SAVOY', 'SAVVY', 'SCALD', 'SCALE', 'SCALP', 'SCALY', 'SCAMP', 'SCANT', 'SCARE',
        'SCARF', 'SCARY', 'SCENE', 'SCENT', 'SCION', 'SCOFF', 'SCOLD', 'SCONE', 'SCOOP', 'SCOOT',
        'SCOPE', 'SCORE', 'SCORN', 'SCOUR', 'SCOUT', 'SCOWL', 'SCRAM', 'SCRAP', 'SCREE', 'SCREW',
        'SCRUB', 'SEDAN', 'SEEDY', 'SEGUE', 'SEIZE', 'SEMEN', 'SENSE', 'SEPIA', 'SERIF', 'SERUM',
        'SERVE', 'SETUP', 'SEVEN', 'SEVER', 'SEWER', 'SHACK', 'SHADE', 'SHADY', 'SHAFT', 'SHAKE',
        'SHAKY', 'SHALE', 'SHALL', 'SHALT', 'SHAME', 'SHANK', 'SHAPE', 'SHARD', 'SHARE', 'SHARK',
        'SHARP', 'SHAVE', 'SHAWL', 'SHEAF', 'SHEAR', 'SHEEN', 'SHEEP', 'SHEER', 'SHEET', 'SHEIK',
        'SHELF', 'SHELL', 'SHIED', 'SHIFT', 'SHINE', 'SHINY', 'SHIRE', 'SHIRK', 'SHIRT', 'SHOAL',
        'SHOCK', 'SHONE', 'SHOOK', 'SHOOT', 'SHORE', 'SHORN', 'SHORT', 'SHOUT', 'SHOVE', 'SHOWN',
        'SHOWY', 'SHRED', 'SHREW', 'SHRUB', 'SHRUG', 'SHUCK', 'SHUNT', 'SHUSH', 'SHYLY', 'SIEGE',
        'SIEVE', 'SIGHT', 'SIGMA', 'SILKY', 'SILLY', 'SINCE', 'SINEW', 'SINGE', 'SINUS', 'SIREN',
        'SISSY', 'SIXTH', 'SIXTY', 'SIZED', 'SKATE', 'SKEIN', 'SKELP', 'SKIER', 'SKIFF', 'SKILL',
        'SKIMP', 'SKIRT', 'SKULK', 'SKULL', 'SKUNK', 'SLACK', 'SLAIN', 'SLANG', 'SLANT', 'SLASH',
        'SLATE', 'SLAVE', 'SLEEK', 'SLEEP', 'SLEET', 'SLEPT', 'SLICE', 'SLICK', 'SLIDE', 'SLIME',
        'SLIMY', 'SLING', 'SLINK', 'SLOPE', 'SLOSH', 'SLOTH', 'SLUMP', 'SLUNG', 'SLUNK', 'SLURP',
        'SLUSH', 'SLYLY', 'SMACK', 'SMALL', 'SMART', 'SMASH', 'SMEAR', 'SMELL', 'SMELT', 'SMILE',
        'SMIRK', 'SMITE', 'SMITH', 'SMOCK', 'SMOKE', 'SMOKY', 'SMOTE', 'SNACK', 'SNAFU', 'SNAIL',
        'SNAKE', 'SNAKY', 'SNARE', 'SNARL', 'SNEAK', 'SNEER', 'SNIDE', 'SNIFF', 'SNIPE', 'SNOOP',
        'SNORE', 'SNORT', 'SNOUT', 'SNOWY', 'SNUCK', 'SNUFF', 'SOAPY', 'SOBER', 'SOGGY', 'SOLAR',
        'SOLID', 'SOLVE', 'SONAR', 'SONIC', 'SOOTH', 'SOOTY', 'SORRY', 'SOUND', 'SOUTH', 'SPACE',
        'SPADE', 'SPARE', 'SPARK', 'SPASM', 'SPAWN', 'SPEAK', 'SPEAR', 'SPECK', 'SPEED', 'SPELL',
        'SPELT', 'SPEND', 'SPENT', 'SPERM', 'SPICE', 'SPICY', 'SPIED', 'SPIEL', 'SPIKE', 'SPIKY',
        'SPILL', 'SPILT', 'SPINE', 'SPINY', 'SPIRE', 'SPITE', 'SPLAT', 'SPLIT', 'SPOIL', 'SPOKE',
        'SPOOF', 'SPOOK', 'SPOOL', 'SPOON', 'SPORE', 'SPORT', 'SPOUT', 'SPRAY', 'SPREE', 'SPRIG',
        'SPUNK', 'SPURN', 'SPURT', 'SQUAD', 'SQUAT', 'SQUID', 'STACK', 'STAFF', 'STAGE', 'STAID',
        'STAIN', 'STAIR', 'STAKE', 'STALE', 'STALK', 'STALL', 'STAMP', 'STAND', 'STANK', 'STAPH',
        'STARE', 'STARK', 'START', 'STASH', 'STATE', 'STAVE', 'STEAD', 'STEAK', 'STEAL', 'STEAM',
        'STEED', 'STEEL', 'STEEP', 'STEER', 'STEIN', 'STERN', 'STICK', 'STIFF', 'STILL', 'STILT',
        'STING', 'STINK', 'STINT', 'STOCK', 'STOIC', 'STOMP', 'STONE', 'STONY', 'STOOD', 'STOOL',
        'STOOP', 'STORE', 'STORK', 'STORM', 'STORY', 'STOUT', 'STOVE', 'STRAP', 'STRAW', 'STRAY',
        'STRIP', 'STRUT', 'STUCK', 'STUDY', 'STUFF', 'STUMP', 'STUNG', 'STUNK', 'STUNT', 'STYLE',
        'SUAVE', 'SUGAR', 'SUITE', 'SULLY', 'SUMAC', 'SUNNY', 'SUPER', 'SURGE', 'SURLY', 'SUSHI',
        'SWAIN', 'SWAMP', 'SWANK', 'SWARD', 'SWARM', 'SWASH', 'SWATH', 'SWEAR', 'SWEAT', 'SWEEP',
        'SWEET', 'SWELL', 'SWEPT', 'SWIFT', 'SWILL', 'SWINE', 'SWING', 'SWIPE', 'SWIRL', 'SWISH',
        'SWISS', 'SWOON', 'SWOOP', 'SWORD', 'SWORE', 'SWORN', 'SWUNG', 'SYNOD', 'SYNTH', 'SYRUP',
        'TABBY', 'TABLE', 'TABOO', 'TACIT', 'TACKY', 'TAFFY', 'TAINT', 'TAKEN', 'TAKER', 'TALLY',
        'TALON', 'TAMER', 'TANGO', 'TANGY', 'TAPER', 'TAPIR', 'TARDY', 'TAROT', 'TARRY', 'TASTE',
        'TASTY', 'TATER', 'TATTY', 'TAUNT', 'TAWNY', 'TAXES', 'TEACH', 'TEASE', 'TEDDY', 'TEENS',
        'TEENY', 'TEETH', 'TEMPO', 'TEMPT', 'TENET', 'TENOR', 'TENSE', 'TENTH', 'TEPEE', 'TEPID',
        'TERRA', 'TERRY', 'TERSE', 'TESLA', 'TESTY', 'TEXAS', 'THANK', 'THEFT', 'THEIR', 'THEME',
        'THERE', 'THESE', 'THETA', 'THICK', 'THIEF', 'THIGH', 'THING', 'THINK', 'THIRD', 'THORN',
        'THOSE', 'THREE', 'THREW', 'THROB', 'THROW', 'THRUM', 'THUMB', 'THUMP', 'THUNK', 'TIARA',
        'TIBIA', 'TIDAL', 'TIGER', 'TIGHT', 'TILDE', 'TIMER', 'TIMID', 'TIMES', 'TINNY', 'TIPSY',
        'TITAN', 'TITHE', 'TITLE', 'TOAST', 'TODAY', 'TODDY', 'TOKEN', 'TONAL', 'TONGA', 'TONIC',
        'TOOTH', 'TOPAZ', 'TOPIC', 'TOPSY', 'TORAH', 'TORCH', 'TORSO', 'TORUS', 'TOTAL', 'TOTEM',
        'TOUCH', 'TOUGH', 'TOWER', 'TOXIC', 'TOXIN', 'TRACE', 'TRACK', 'TRACT', 'TRADE', 'TRAIL',
        'TRAIN', 'TRAIT', 'TRAMP', 'TRASH', 'TRAWL', 'TREAD', 'TREAT', 'TREND', 'TRIAD', 'TRIAL',
        'TRIBE', 'TRICE', 'TRICK', 'TRIED', 'TRIER', 'TRIES', 'TRILL', 'TRIPE', 'TRITE', 'TROLL',
        'TROOP', 'TROPE', 'TROUT', 'TROVE', 'TRUCE', 'TRUCK', 'TRULY', 'TRUMP', 'TRUNK', 'TRUSS',
        'TRUST', 'TRUTH', 'TRYST', 'TUBAL', 'TUBBY', 'TUBER', 'TULIP', 'TULLE', 'TUMOR', 'TUNIC',
        'TURBO', 'TUSHY', 'TUTOR', 'TWAIN', 'TWANG', 'TWEAK', 'TWEED', 'TWEET', 'TWERP', 'TWICE',
        'TWIGS', 'TWINE', 'TWINS', 'TWIRL', 'TWIST', 'TWITS', 'TWIXT', 'TYING', 'UDDER', 'ULCER',
        'ULTRA', 'UMAMI', 'UMBRA', 'UNCLE', 'UNDER', 'UNDUE', 'UNFED', 'UNFIT', 'UNIFY', 'UNION',
        'UNITE', 'UNITY', 'UNLIT', 'UNMET', 'UNSAY', 'UNSET', 'UNTIE', 'UNTIL', 'UNWED', 'UNZIP',
        'UPEND', 'UPPER', 'UPSET', 'URBAN', 'URGED', 'URINE', 'USAGE', 'USHER', 'USING', 'USUAL',
        'USURP', 'USURY', 'UTILE', 'UTTER', 'VAGUE', 'VALID', 'VALOR', 'VALUE', 'VALVE', 'VAPOR',
        'VAULT', 'VAUNT', 'VEGAN', 'VENOM', 'VENUE', 'VENUS', 'VERGE', 'VERSE', 'VERSO', 'VERVE',
        'VEXED', 'VIBES', 'VICAR', 'VIDEO', 'VIGIL', 'VIGOR', 'VILLA', 'VINYL', 'VIOLA', 'VIPER',
        'VIRAL', 'VIRUS', 'VISIT', 'VISOR', 'VISTA', 'VITAL', 'VIVID', 'VIXEN', 'VOCAL', 'VODKA',
        'VOGUE', 'VOICE', 'VOILA', 'VOMIT', 'VOTER', 'VOUCH', 'VOWEL', 'VYING', 'WACKY', 'WADER',
        'WAFER', 'WAGER', 'WAGON', 'WAIST', 'WAIVE', 'WAKEN', 'WALER', 'WALTZ', 'WARTY', 'WASTE',
        'WATCH', 'WATER', 'WAVER', 'WAXED', 'WAXEN', 'WEARY', 'WEAVE', 'WEBER', 'WEDGE', 'WEEDY',
        'WEIGH', 'WEIRD', 'WELSH', 'WENCH', 'WHALE', 'WHARF', 'WHEAT', 'WHEEL', 'WHELP', 'WHERE',
        'WHICH', 'WHIFF', 'WHILE', 'WHINE', 'WHINY', 'WHIRL', 'WHISK', 'WHITE', 'WHOLE', 'WHOOP',
        'WHORE', 'WHOSE', 'WIDEN', 'WIDER', 'WIDOW', 'WIDTH', 'WIELD', 'WIGHT', 'WILLY', 'WIMPY',
        'WINCE', 'WINCH', 'WINDY', 'WIPED', 'WIPER', 'WIRED', 'WIRER', 'WISER', 'WITCH', 'WITTY',
        'WOKEN', 'WOMAN', 'WOMEN', 'WOODY', 'WOOER', 'WOOLY', 'WOOZY', 'WORDY', 'WORLD', 'WORMY',
        'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD', 'WOUND', 'WOVEN', 'WRACK', 'WRATH', 'WREAK',
        'WRECK', 'WREST', 'WRING', 'WRIST', 'WRITE', 'WRONG', 'WROTE', 'WRUNG', 'WRYLY', 'XENON',
        'YACHT', 'YAHOO', 'YEAST', 'YEARN', 'YEARS', 'YIELD', 'YODEL', 'YOKED', 'YOKEL', 'YOUNG',
        'YOURS', 'YOUTH', 'YUCCA', 'YUCKY', 'YUMMY', 'ZEBRA', 'ZESTY', 'ZIPPY', 'ZONED', 'ZOOMS'],


    6: ['ACCEPT', 'ACCESS', 'ACROSS', 'ACTING', 'ACTION', 'ACTIVE', 'ACTUAL', 'ADVICE', 'ADVISE', 'AFFECT',
        'AFFORD', 'AFRAID', 'AGENCY', 'AGENDA', 'ALMOST', 'ALWAYS', 'AMOUNT', 'ANIMAL', 'ANNUAL', 'ANSWER',
        'ANYONE', 'ANYWAY', 'APPEAL', 'APPEAR', 'AROUND', 'ARRIVE', 'ARTIST', 'ASPECT', 'ASSESS', 'ASSIGN',
        'ASSIST', 'ASSUME', 'ASSURE', 'ATTACH', 'ATTACK', 'ATTEND', 'AUTHOR', 'AVENUE', 'BACKED', 'BARELY',
        'BATTLE', 'BEAUTY', 'BECAME', 'BECOME', 'BEFORE', 'BEHALF', 'BEHIND', 'BELIEF', 'BELONG', 'BERLIN',
        'BETTER', 'BEYOND', 'BISHOP', 'BORDER', 'BOTTLE', 'BOTTOM', 'BOUGHT', 'BRANCH', 'BREAST', 'BREATH',
        'BRIDGE', 'BRIGHT', 'BROKEN', 'BUDGET', 'BURDEN', 'BUREAU', 'BUTTON', 'CAMERA', 'CANCER', 'CANNOT',
        'CARBON', 'CAREER', 'CASTLE', 'CASUAL', 'CAUGHT', 'CENTER', 'CENTRE', 'CHANCE', 'CHANGE', 'CHARGE',
        'CHOICE', 'CHOOSE', 'CHOSEN', 'CHURCH', 'CIRCLE', 'CLIENT', 'CLOSED', 'CLOSER', 'COFFEE', 'COLUMN',
        'COMBAT', 'COMING', 'COMMON', 'COMPLY', 'COPPER', 'CORNER', 'COSTLY', 'COUPLE', 'COURSE', 'COVERS',
        'CREATE', 'CREDIT', 'CRISIS', 'CUSTOM', 'DAMAGE', 'DANGER', 'DEALER', 'DEBATE', 'DECADE', 'DECIDE',
        'DEFEAT', 'DEFEND', 'DEFINE', 'DEGREE', 'DEMAND', 'DEPEND', 'DEPUTY', 'DERIVE', 'DESIGN', 'DESIRE',
        'DETAIL', 'DETECT', 'DEVICE', 'DIFFER', 'DINNER', 'DIRECT', 'DOCTOR', 'DOLLAR', 'DOMAIN', 'DOUBLE',
        'DRIVEN', 'DRIVER', 'DURING', 'EASILY', 'EATING', 'EDITOR', 'EFFECT', 'EFFORT', 'EIGHTH', 'EITHER',
        'EMERGE', 'EMPIRE', 'EMPLOY', 'ENABLE', 'ENDING', 'ENERGY', 'ENGAGE', 'ENGINE', 'ENOUGH', 'ENSURE',
        'ENTIRE', 'ENTITY', 'EQUITY', 'ESCAPE', 'ESTATE', 'ETHNIC', 'EUROPE', 'EVENTS', 'EXCEED', 'EXCEPT',
        'EXCESS', 'EXPAND', 'EXPECT', 'EXPERT', 'EXPORT', 'EXTEND', 'EXTENT', 'FABRIC', 'FACING', 'FACTOR',
        'FAILED', 'FAIRLY', 'FALLEN', 'FAMILY', 'FAMOUS', 'FATHER', 'FELLOW', 'FEMALE', 'FIGURE', 'FILING',
        'FINGER', 'FINISH', 'FISCAL', 'FLIGHT', 'FLYING', 'FOLLOW', 'FORCED', 'FOREST', 'FORGET', 'FORMAL',
        'FORMAT', 'FORMED', 'FORMER', 'FOSTER', 'FOUGHT', 'FOURTH', 'FRANCE', 'FRENCH', 'FRIEND', 'FUTURE',
        'GARDEN', 'GATHER', 'GENDER', 'GERMAN', 'GLOBAL', 'GOLDEN', 'GROUND', 'GROWTH', 'GUIDED', 'HANDLE',
        'HANDED', 'HAPPEN', 'HARDLY', 'HEADED', 'HEALTH', 'HEARTS', 'HEIGHT', 'HELPED', 'HIDDEN', 'HOLDER',
        'HONEST', 'IMPACT', 'IMPORT', 'INCOME', 'INDEED', 'INJURY', 'INSIDE', 'INTEND', 'INTENT', 'INVEST',
        'ISLAND', 'ITSELF', 'JERSEY', 'JOHNNY', 'JOINED', 'JOSEPH', 'JUNIOR', 'KILLED', 'LABOUR', 'LADDER',
        'LAUNCH', 'LAWYER', 'LEADER', 'LEAGUE', 'LEAVES', 'LEGACY', 'LENGTH', 'LESSON', 'LETTER', 'LIGHTS',
        'LIKELY', 'LINKED', 'LISTEN', 'LITTLE', 'LIVING', 'LOCKED', 'LONDON', 'LOSING', 'LOVELY', 'LOVING',
        'LUXURY', 'MAKING', 'MANAGE', 'MANNER', 'MANUAL', 'MARGIN', 'MARINE', 'MARKED', 'MARKET', 'MASTER',
        'MATTER', 'MATURE', 'MEDIUM', 'MEMBER', 'MEMORY', 'MENTAL', 'MERELY', 'MERGER', 'METHOD', 'MIDDLE',
        'MILLER', 'MINING', 'MINUTE', 'MIRROR', 'MOBILE', 'MODERN', 'MODEST', 'MODULE', 'MOMENT', 'MORRIS',
        'MOSTLY', 'MOTHER', 'MOTION', 'MOVING', 'MURDER', 'MUSEUM', 'MUTUAL', 'MYSELF', 'NARROW', 'NATION',
        'NATIVE', 'NATURE', 'NEARBY', 'NEARLY', 'NIGHTS', 'NOBODY', 'NORMAL', 'NOTICE', 'NOTION', 'NUMBER',
        'OBJECT', 'OBTAIN', 'OFFICE', 'OFFSET', 'ONLINE', 'OPTION', 'ORANGE', 'ORIGIN', 'OUTPUT', 'OXFORD',
        'PACKED', 'PALACE', 'PARENT', 'PARTLY', 'PASSED', 'PATENT', 'PEOPLE', 'PERIOD', 'PERMIT', 'PERSON',
        'PHRASE', 'PICKED', 'PLANET', 'PLAYER', 'PLEASE', 'PLENTY', 'POCKET', 'POLICE', 'POLICY', 'PREFER',
        'PRETTY', 'PRINCE', 'PRISON', 'PROFIT', 'PROPER', 'PROVEN', 'PUBLIC', 'PURELY', 'PURPLE', 'PURSUE',
        'RAISED', 'RANDOM', 'RARELY', 'RATHER', 'RATING', 'READER', 'REALLY', 'REASON', 'RECALL', 'RECENT',
        'RECORD', 'REDUCE', 'REFORM', 'REGARD', 'REGIME', 'REGION', 'RELATE', 'RELIEF', 'REMAIN', 'REMARK',
        'REMOTE', 'REMOVE', 'REPAIR', 'REPEAT', 'REPLAY', 'REPORT', 'RESCUE', 'RESORT', 'RESULT', 'RESUME',
        'RETAIL', 'RETAIN', 'RETURN', 'REVEAL', 'REVIEW', 'REWARD', 'RIDING', 'RISING', 'ROBUST', 'RULING',
        'RUSSIA', 'SAFETY', 'SALARY', 'SAMPLE', 'SAVING', 'SAYING', 'SCHEME', 'SCHOOL', 'SCREEN', 'SCRIPT',
        'SEARCH', 'SEASON', 'SECOND', 'SECRET', 'SECTOR', 'SECURE', 'SEEING', 'SEEMED', 'SELECT', 'SELLER',
        'SENIOR', 'SERIES', 'SERVED', 'SERVER', 'SETTLE', 'SEVERE', 'SEXUAL', 'SHOULD', 'SIGNAL', 'SIGNED',
        'SILENT', 'SILVER', 'SIMPLE', 'SIMPLY', 'SINGLE', 'SISTER', 'SLIGHT', 'SMOOTH', 'SOCIAL', 'SOLELY',
        'SOUGHT', 'SOURCE', 'SOVIET', 'SPEECH', 'SPIRIT', 'SPOKEN', 'SPREAD', 'SPRING', 'SQUARE', 'STABLE',
        'STATUS', 'STEADY', 'STOLEN', 'STRAIN', 'STREAM', 'STREET', 'STRESS', 'STRICT', 'STRIKE', 'STRING',
        'STRONG', 'STRUCK', 'STUDIO', 'SUBMIT', 'SUDDEN', 'SUFFER', 'SUMMER', 'SUMMIT', 'SUPPLY', 'SURELY',
        'SURVEY', 'SWITCH', 'SYMBOL', 'SYSTEM', 'TAKING', 'TALENT', 'TARGET', 'TAUGHT', 'TENANT', 'TENDER',
        'TENNIS', 'THANKS', 'THEORY', 'THIRTY', 'THOUGH', 'THREAD', 'THREAT', 'THROWN', 'TICKET', 'TIMBER',
        'TIMING', 'TISSUE', 'TOWARD', 'TRAVEL', 'TREATY', 'TRYING', 'TURNER', 'TWENTY', 'UNABLE', 'UNIQUE',
        'UNITED', 'UNLESS', 'UNLIKE', 'UPDATE', 'USEFUL', 'VALLEY', 'VARIED', 'VENDOR', 'VICTIM', 'VISION',
        'VISUAL', 'VOLUME', 'WALKER', 'WEALTH', 'WEAPON', 'WEEKLY', 'WEIGHT', 'WHOLLY', 'WINDOW', 'WINNER',
        'WINTER', 'WITHIN', 'WONDER', 'WOODEN', 'WORKER', 'WRITER', 'YELLOW'],

    7: ['ABILITY', 'ABSENCE', 'ACADEMY', 'ACCOUNT', 'ACCUSED', 'ACHIEVE', 'ACQUIRE', 'ADDRESS', 'ADVANCE', 'ADVERSE',
        'ADVISED', 'ADVISER', 'AGAINST', 'AIRLINE', 'AIRPORT', 'ALCOHOL', 'ALLEGED', 'ALREADY', 'ANALYST', 'ANCIENT',
        'ANOTHER', 'ANXIETY', 'ANXIOUS', 'ANYBODY', 'APPLIED', 'APPOINT', 'APPROVE', 'ARRANGE', 'ARRIVAL', 'ARTICLE',
        'ASSAULT', 'AVERAGE', 'BALANCE', 'BANKING', 'BARRIER', 'BATTERY', 'BEARING', 'BECAUSE', 'BEDROOM', 'BENEATH',
        'BENEFIT', 'BESIDES', 'BETWEEN', 'BILLION', 'BINDING', 'BROTHER', 'BROUGHT', 'BURNING', 'CABINET', 'CAPABLE',
        'CAPITAL', 'CAPTAIN', 'CAPTURE', 'CAREFUL', 'CARRIER', 'CENTRAL', 'CENTURY', 'CERTAIN', 'CHAMBER', 'CHANNEL',
        'CHAPTER', 'CHARITY', 'CHARTER', 'CHICKEN', 'CIRCUIT', 'CITIZEN', 'CLASSIC', 'CLIMATE', 'CLOSING', 'CLOSURE',
        'CLOTHES', 'COLLECT', 'COLLEGE', 'COMBINE', 'COMFORT', 'COMMAND', 'COMMENT', 'COMPACT', 'COMPANY', 'COMPARE',
        'COMPETE', 'COMPLEX', 'CONCEPT', 'CONCERN', 'CONCERT', 'CONDUCT', 'CONFIRM', 'CONNECT', 'CONSENT', 'CONSIST',
        'CONTACT', 'CONTAIN', 'CONTENT', 'CONTEST', 'CONTEXT', 'CONTROL', 'CONVERT', 'CORRECT', 'COUNCIL', 'COUNSEL',
        'COUNTRY', 'COURAGE', 'CREATOR', 'CRICKET', 'CRUCIAL', 'CULTURE', 'CURRENT', 'CUSTODY', 'CUTTING', 'DEALING',
        'DECLINE', 'DEFAULT', 'DEFENCE', 'DEFICIT', 'DELIVER', 'DENSITY', 'DEPOSIT', 'DESKTOP', 'DESPITE', 'DESTROY',
        'DEVELOP', 'DEVOTED', 'DIAMOND', 'DIGITAL', 'DISPLAY', 'DISPUTE', 'DISTANT', 'DIVERSE', 'DIVIDED', 'DRAWING',
        'DRIVING', 'EASTERN', 'ECONOMY', 'EDITION', 'ELEMENT', 'EMBRACE', 'EMOTION', 'EMPEROR', 'ENGAGED', 'ENHANCE',
        'ENQUIRY', 'EPISODE', 'ESSENCE', 'EVENING', 'EVIDENT', 'EXACTLY', 'EXAMINE', 'EXAMPLE', 'EXCITED', 'EXCLUDE',
        'EXECUTE', 'EXHIBIT', 'EXPLAIN', 'EXPLORE', 'EXPRESS', 'EXTREME', 'FACTORY', 'FACULTY', 'FAILURE', 'FALLING',
        'FASHION', 'FEATURE', 'FEDERAL', 'FEELING', 'FICTION', 'FIFTEEN', 'FILLING', 'FINANCE', 'FINDING', 'FISHING',
        'FITNESS', 'FOREIGN', 'FOREVER', 'FORMULA', 'FORTUNE', 'FORWARD', 'FOUNDER', 'FREEDOM', 'FURTHER', 'GALLERY',
        'GENERAL', 'GENUINE', 'GETTING', 'WORKING', 'GROWING', 'HABITAT', 'HANGING', 'HEADING', 'HEALTHY', 'HEARING',
        'HEAVILY', 'HELPFUL', 'HERSELF', 'HIGHWAY', 'HIMSELF', 'HISTORY', 'HOLDING', 'HOLIDAY', 'HORIZON', 'HOSTILE',
        'HOUSING', 'HOWEVER', 'HUNDRED', 'HUSBAND', 'ILLEGAL', 'ILLNESS', 'IMAGINE', 'IMPROVE', 'INCLUDE', 'INITIAL',
        'INQUIRY', 'INSTALL', 'INSTANT', 'INSTEAD', 'INTENSE', 'INTERIM', 'INVOLVE', 'ISOLATE', 'JOURNAL', 'JOURNEY',
        'JUSTICE', 'JUSTIFY', 'KEEPING', 'KILLING', 'KINGDOM', 'KITCHEN', 'KNOWING', 'LANDING', 'LARGELY', 'LASTING',
        'LEADING', 'LEARNED', 'LEATHER', 'LEAVING', 'LECTURE', 'LEISURE', 'LIBERAL', 'LIBRARY', 'LICENSE', 'LIMITED',
        'LINKING', 'LISTING', 'LITERAL', 'LOADING', 'LOCATED', 'LOCKING', 'LOGICAL', 'LOOKING', 'LOYALTY', 'MACHINE',
        'MANAGER', 'MARRIED', 'MASSIVE', 'MATCHED', 'MAXIMUM', 'MEANING', 'MEASURE', 'MEDICAL', 'MEETING', 'MESSAGE',
        'MILLION', 'MINIMAL', 'MINIMUM', 'MISSING', 'MISSION', 'MISTAKE', 'MIXTURE', 'MONITOR', 'MORNING', 'MUSICAL',
        'MYSTERY', 'NATURAL', 'NERVOUS', 'NETWORK', 'NEUTRAL', 'NOMINAL', 'NOTHING', 'NOWHERE', 'NUCLEAR', 'NURSING',
        'OBVIOUS', 'OFFENCE', 'OFFICER', 'ONGOING', 'OPENING', 'OPERATE', 'OPINION', 'OPTICAL', 'ORGANIC', 'OUTCOME',
        'OUTDOOR', 'OUTLOOK', 'OUTSIDE', 'OVERALL', 'PACKAGE', 'PAINTED', 'PAINTER', 'PARKING', 'PARTIAL', 'PARTNER',
        'PASSAGE', 'PASSING', 'PASSION', 'PASSIVE', 'PATIENT', 'PATTERN', 'PAYMENT', 'PENALTY', 'PENSION', 'PERCENT',
        'PERFECT', 'PERFORM', 'PERHAPS', 'PERSIST', 'PICKING', 'PICTURE', 'PIONEER', 'PLASTIC', 'PLAYING', 'PLEASED',
        'POINTED', 'POPULAR', 'PORTION', 'POVERTY', 'PRECISE', 'PREDICT', 'PREMIER', 'PREMIUM', 'PREPARE', 'PRESENT',
        'PRESSED', 'PREVENT', 'PRIMARY', 'PRINTED', 'PRINTER', 'PRIVACY', 'PRIVATE', 'PROBLEM', 'PROCEED', 'PROCESS',
        'PRODUCE', 'PRODUCT', 'PROFILE', 'PROGRAM', 'PROJECT', 'PROMISE', 'PROMOTE', 'PROPOSE', 'PROTECT', 'PROTEIN',
        'PROTEST', 'PROVIDE', 'PUBLISH', 'PURPOSE', 'PUSHING', 'PUTTING', 'QUALITY', 'QUARTER', 'QUICKLY', 'RADICAL',
        'RAILWAY', 'RANKING', 'RAPIDLY', 'READING', 'REALITY', 'REALIZE', 'RECEIPT', 'RECEIVE', 'RECOVER', 'REDUCED',
        'REFLECT', 'REFUGEE', 'REFUSED', 'REGULAR', 'RELATED', 'RELEASE', 'REMOVAL', 'REMOVED', 'REPLACE', 'REPLIED',
        'REQUEST', 'REQUIRE', 'RESERVE', 'RESOLVE', 'RESPECT', 'RESPOND', 'RESTORE', 'RETIRED', 'RETREAT', 'REVENUE',
        'REVERSE', 'REVISED', 'ROUTINE', 'RUNNING', 'RUSSIAN', 'SATISFY', 'SCANDAL', 'SCHOLAR', 'SCIENCE', 'SECTION',
        'SEGMENT', 'SELLING', 'SERIOUS', 'SERVANT', 'SERVICE', 'SESSION', 'SETTING', 'SETTLED', 'SEVERAL', 'SHAKING',
        'SHAPING', 'SHARING', 'SHELTER', 'SHINING', 'SHOCKED', 'SHORTLY', 'SHOWING', 'SIBLING', 'SILENCE', 'SIMILAR',
        'SITTING', 'SKILLED', 'SMOKING', 'SOCIETY', 'SOLDIER', 'SOMEHOW', 'SOMEONE', 'SPANISH', 'SPEAKER', 'SPECIAL',
        'SPECIES', 'SPONSOR', 'STATION', 'STRANGE', 'STUDENT', 'SUBJECT', 'SUCCEED', 'SUCCESS', 'SUGGEST', 'SUMMARY',
        'SUPPORT', 'SUPPOSE', 'SUPREME', 'SURFACE', 'SURGERY', 'SURPLUS', 'SURVIVE', 'SUSPECT', 'SUSTAIN', 'TALKING',
        'TEACHER', 'TELECOM', 'TELLING', 'THEATRE', 'THERAPY', 'THEREBY', 'THOUGHT', 'THROUGH', 'TONIGHT', 'TOTALLY',
        'TOUCHED', 'TOWARDS', 'TRADING', 'TRAFFIC', 'TRAINED', 'TRAINER', 'TREATED', 'TRIUMPH', 'TROUBLE', 'TURNING',
        'TYPICAL', 'UNIFORM', 'UNKNOWN', 'UNUSUAL', 'UPGRADE', 'UPWARDS', 'UTILITY', 'VARIETY', 'VARIOUS', 'VEHICLE',
        'VENTURE', 'VERSION', 'VETERAN', 'VICTORY', 'VILLAGE', 'VINTAGE', 'VIOLENT', 'VIRTUAL', 'VISIBLE', 'VISITOR',
        'WAITING', 'WALKING', 'WANTING', 'WARNING', 'WARRANT', 'WEALTHY', 'WEARING', 'WEATHER', 'WEDDING', 'WEEKEND',
        'WELCOME', 'WELFARE', 'WESTERN', 'WHETHER', 'WILLING', 'WINNING', 'WITHOUT', 'WITNESS', 'WRITING', 'WRITTEN'],

    8: ['ABSOLUTE', 'ABSTRACT', 'ACADEMIC', 'ACCEPTED', 'ACCIDENT', 'ACCURACY', 'ACCURATE', 'ACHIEVED', 'ACQUIRED', 'ACTIVITY',
        'ACTUALLY', 'ADDITION', 'ADEQUATE', 'ADJACENT', 'ADJUSTED', 'ADMITTED', 'ADVANCED', 'ADVISORY', 'ADVOCATE', 'AFFECTED',
        'AIRCRAFT', 'ALLIANCE', 'ALTHOUGH', 'ALUMINUM', 'ANALYSIS', 'ANNOUNCE', 'ANYTHING', 'ANYWHERE', 'APPARENT', 'APPENDIX',
        'APPETITE', 'APPROACH', 'APPROVAL', 'ARGUMENT', 'ARTISTIC', 'ASSEMBLY', 'ASSUMING', 'ATHLETIC', 'ATTACHED', 'ATTITUDE',
        'ATTORNEY', 'AUDIENCE', 'AUTONOMY', 'BACHELOR', 'BACKDROP', 'BACKWARD', 'BACTERIA', 'BALANCED', 'BATHROOM', 'BECOMING',
        'BEHAVIOR', 'BELIEVED', 'BIRTHDAY', 'BOUNDARY', 'BREAKING', 'BREEDING', 'BRIEFING', 'BRINGING', 'BUILDING', 'BULLETIN',
        'BUSINESS', 'CALENDAR', 'CAMPAIGN', 'CAPACITY', 'CASUALTY', 'CATCHING', 'CATEGORY', 'CATHOLIC', 'CAUTIOUS', 'CELLULAR',
        'CEREMONY', 'CHAIRMAN', 'CHAMPION', 'CHANGING', 'CHEMICAL', 'CHILDREN', 'CIRCULAR', 'CITATION', 'CIVILIAN', 'CLEANING',
        'CLEARING', 'CLIMBING', 'CLINICAL', 'CLOTHING', 'COLLAPSE', 'COLONIAL', 'COMBINED', 'COMMERCE', 'COMMONLY', 'COMPLETE',
        'COMPOUND', 'COMPUTER', 'CONCLUDE', 'CONCRETE', 'CONFLICT', 'CONFUSED', 'CONGRESS', 'CONSIDER', 'CONSTANT', 'CONSUMER',
        'CONTEMPT', 'CONTINUE', 'CONTRACT', 'CONTRARY', 'CONTRAST', 'CONVINCE', 'CORRIDOR', 'COVERAGE', 'COVERING', 'CREATION',
        'CREATIVE', 'CREATURE', 'CRIMINAL', 'CRITICAL', 'CROSSING', 'CULTURAL', 'CURRENCY', 'CUSTOMER', 'DATABASE', 'DAUGHTER',
        'DEADLINE', 'DECIDING', 'DECISION', 'DECISIVE', 'DECLARED', 'DECREASE', 'DELIVERY', 'DEPARTED', 'DESCRIBE', 'DESIGNER',
        'DETAILED', 'DETECTOR', 'DIALOGUE', 'DIAMETER', 'DIRECTLY', 'DIRECTOR', 'DISABLED', 'DISASTER', 'DISCLOSE', 'DISCOUNT',
        'DISCOVER', 'DISORDER', 'DISPOSAL', 'DISTANCE', 'DISTINCT', 'DISTRICT', 'DIVIDEND', 'DIVISION', 'DOCTRINE', 'DOCUMENT',
        'DOMESTIC', 'DOMINANT', 'DOMINATE', 'DRAMATIC', 'DRESSING', 'DROPPING', 'DURATION', 'DYNAMICS', 'EARNINGS', 'ECONOMIC',
        'EDUCATED', 'ELECTION', 'ELECTRIC', 'ELIGIBLE', 'EMERGING', 'EMISSION', 'EMPHASIS', 'EMPLOYEE', 'ENDEAVOR', 'ENGAGING',
        'ENGINEER', 'ENORMOUS', 'ENTIRELY', 'ENTRANCE', 'ENVELOPE', 'EQUALITY', 'EQUATION', 'EQUIPPED', 'ESTIMATE', 'EVALUATE',
        'EVENTUAL', 'EVERYDAY', 'EVERYONE', 'EVIDENCE', 'EXAMINED', 'EXCHANGE', 'EXCITING', 'EXCLUDED', 'EXERCISE', 'EXPLICIT',
        'EXPLORER', 'EXPOSURE', 'EXTENDED', 'EXTERNAL', 'FACILITY', 'FAMILIAR', 'FEATURED', 'FEEDBACK', 'FESTIVAL', 'FINISHED',
        'FLEXIBLE', 'FLOATING', 'FOOTBALL', 'FOOTSTEP', 'FORECAST', 'FORESTRY', 'FORMERLY', 'FRACTION', 'FRAGMENT', 'FREQUENT',
        'FRIENDLY', 'FRONTIER', 'FUNCTION', 'GENERATE', 'GENEROUS', 'GOVERNOR', 'GRADUATE', 'GRAPHICS', 'GRATEFUL', 'GREATEST',
        'GRINDING', 'GROUNDED', 'GUARDIAN', 'GUIDANCE', 'HANDLING', 'HARDWARE', 'HEADLINE', 'HISTORIC', 'HOMELESS', 'HOSPITAL',
        'IDENTITY', 'IDEOLOGY', 'IMPERIAL', 'IMPLICIT', 'INCIDENT', 'INCLUDES', 'INCREASE', 'INDICATE', 'INDIRECT', 'INDUSTRY',
        'INFORMAL', 'INFORMED', 'INHERENT', 'INNOCENT', 'INSTANCE', 'INSTINCT', 'INTEGRAL', 'INTENDED', 'INTEREST', 'INTERIOR',
        'INTERNAL', 'INTERNET', 'INTERVAL', 'INTIMATE', 'INVASION', 'INVOLVED', 'ISOLATED', 'JUDGMENT', 'JUDICIAL', 'JUNCTION',
        'KEYBOARD', 'LANDLORD', 'LANDMARK', 'LANGUAGE', 'LAUGHTER', 'LEARNING', 'LIGHTING', 'LIKEWISE', 'LIMITING', 'LITERARY',
        'LOCATION', 'MAGAZINE', 'MAGNETIC', 'MAINTAIN', 'MAJORITY', 'MARGINAL', 'MARRIAGE', 'MATERIAL', 'MATERNAL', 'MAXIMIZE',
        'MEANTIME', 'MEASURED', 'MECHANIC', 'MEDIEVAL', 'MEMORIAL', 'MERCHANT', 'MIDNIGHT', 'MILITARY', 'MINIMIZE', 'MINISTER',
        'MINORITY', 'MOBILITY', 'MODERATE', 'MODIFIED', 'MONARCHY', 'MONETARY', 'MOREOVER', 'MORTGAGE', 'MOUNTAIN', 'MOVEMENT',
        'MULTIPLE', 'NATIONAL', 'NEGATIVE', 'NEIGHBOR', 'NORTHERN', 'NOTEBOOK', 'NUMEROUS', 'OBSERVER', 'OBSTACLE', 'OBTAINED',
        'OCCASION', 'OCCUPIED', 'OFFERING', 'OFFICIAL', 'OFFSHORE', 'OPERATOR', 'OPPONENT', 'OPPOSITE', 'OPTIMISM', 'OPTIONAL',
        'ORDINARY', 'ORGANIZE', 'ORIGINAL', 'OUTBREAK', 'OUTGOING', 'OVERCOME', 'OVERHEAD', 'OVERSEAS', 'OVERVIEW', 'PAINTING',
        'PARALLEL', 'PARENTAL', 'PARTICLE', 'PATIENCE', 'PEACEFUL', 'PECULIAR', 'PERSONAL', 'PERSUADE', 'PETITION', 'PHARMACY',
        'PHYSICAL', 'PLATFORM', 'PLEASANT', 'PLEASURE', 'POINTING', 'PORTRAIT', 'POSITIVE', 'POSSIBLE', 'POSSIBLY', 'POSTCARD',
        'POWERFUL', 'PRACTICE', 'PRECIOUS', 'PREGNANT', 'PRESENCE', 'PRESERVE', 'PRESSING', 'PRESSURE', 'PREVIOUS', 'PRINCESS',
        'PRINTING', 'PRIORITY', 'PRISONER', 'PROBABLY', 'PROFOUND', 'PROGRESS', 'PROMISED', 'PROPERLY', 'PROPERTY', 'PROPOSAL',
        'PROSPECT', 'PROTOCOL', 'PROVIDED', 'PROVINCE', 'PUBLICLY', 'PURCHASE', 'PURSUING', 'QUANTITY', 'QUESTION', 'RATIONAL',
        'REACTION', 'RECEIVED', 'RECEIVER', 'RECENTLY', 'RECEPTOR', 'RECOVERY', 'REFERRED', 'REGIONAL', 'REGISTER', 'RELATION',
        'RELATIVE', 'RELEVANT', 'RELIABLE', 'RELIANCE', 'REMEMBER', 'REPEATED', 'REPLACED', 'REPORTER', 'REPUBLIC', 'REQUIRED',
        'RESEARCH', 'RESERVED', 'RESIDENT', 'RESIGNED', 'RESOLVED', 'RESOURCE', 'RESPONSE', 'RESTORED', 'RESTRICT', 'RETAINED',
        'RETIRING', 'RETRIEVE', 'RETURNED', 'REVEALED', 'REVEREND', 'REVISION', 'RHETORIC', 'ROMANTIC', 'ROTATION', 'SCENARIO',
        'SCHEDULE', 'SEASONAL', 'SECRETLY', 'SECURITY', 'SELECTED', 'SENSIBLE', 'SENTENCE', 'SEPARATE', 'SEQUENCE', 'SERGEANT',
        'SETTLING', 'SEVERELY', 'SEXUALLY', 'SHOOTING', 'SHORTAGE', 'SHOULDER', 'SHOUTING', 'SHUTDOWN', 'SIBLINGS', 'SICKNESS',
        'SIDEWALK', 'SIMPLIFY', 'SITUATED', 'SLIGHTLY', 'SMALLEST', 'SOFTWARE', 'SOLUTION', 'SOMEBODY', 'SOMEWHAT', 'SOUTHERN',
        'SPEAKING', 'SPECIFIC', 'SPECTRUM', 'SPENDING', 'SPORTING', 'STANDARD', 'STANDING', 'STARTING', 'STEAMING', 'STIMULUS',
        'STRAIGHT', 'STRANGER', 'STRATEGY', 'STRENGTH', 'STRIKING', 'STRONGLY', 'STRUGGLE', 'STUDYING', 'STUNNING', 'SUBURBAN',
        'SUDDENLY', 'SUFFERED', 'SUITABLE', 'SUPERIOR', 'SUPPOSED', 'SURGICAL', 'SURPRISE', 'SURVIVAL', 'SURVIVOR', 'SWIMMING',
        'SYMBOLIC', 'SYMPATHY', 'SYNDROME', 'TACTICAL', 'TANGIBLE', 'TAXATION', 'TEACHING', 'TEAMMATE', 'TEENAGER', 'TENDENCY',
        'TERMINAL', 'TERRIBLE', 'THINKING', 'THOROUGH', 'THOUSAND', 'THREATEN', 'TOGETHER', 'TOMORROW', 'TOUCHING', 'TRACKING',
        'TRAINING', 'TRANSFER', 'TREATING', 'TRIANGLE', 'TRIBUNAL', 'TROPICAL', 'TROUBLED', 'ULTIMATE', 'UMBRELLA', 'UNCOMMON',
        'UNDERLIE', 'UNIVERSE', 'UNLIKELY', 'UPSTAIRS', 'VALUABLE', 'VARIABLE', 'VARIANCE', 'VELOCITY', 'VERTICAL', 'VICINITY',
        'VIOLENCE', 'VISITING', 'VOLCANIC', 'WARRANTY', 'WATCHING', 'WEAKNESS', 'WHATEVER', 'WHENEVER', 'WHEREVER', 'WILDLIFE',
        'WIRELESS', 'WITHDRAW', 'WOODLAND', 'WORKSHOP', 'YOURSELF'],

};

// Game state
let gameState = {
    wordLength: 5,
    maxAttempts: 6,
    currentWord: '',
    currentRow: 0,
    currentTile: 0,
    gameOver: false,
    letterStatus: {},
    customWord: false
};

// Encode/Decode functions for URL sharing
function encodeWord(word) {
    return btoa(word);
}

function decodeWord(encoded) {
    try {
        return atob(encoded);
    } catch (e) {
        return null;
    }
}

// Get custom word from URL parameter
function getCustomWordFromURL() {
    const urlParams = new URLSearchParams(window.location.search);
    const encodedWord = urlParams.get('w');
    if (encodedWord) {
        const word = decodeWord(encodedWord);
        if (word && /^[A-Z]+$/.test(word) && word.length >= 4 && word.length <= 8) {
            return word;
        }
    }
    return null;
}

// Initialize game
document.addEventListener('DOMContentLoaded', () => {
    initializeGame();
    setupEventListeners();
    setupCustomWordUI();
});

function initializeGame() {
    const customWord = getCustomWordFromURL();
    let wordLength, targetWord, isCustom = false;

    if (customWord) {
        // Use custom word from URL
        wordLength = customWord.length;
        targetWord = customWord;
        isCustom = true;
        document.getElementById('wordLength').value = wordLength;
        // Hide custom word UI when playing a challenge
        document.getElementById('customWordSection').style.display = 'none';
    } else {
        // Random word
        wordLength = parseInt(document.getElementById('wordLength').value);
        const wordList = WORD_LISTS[wordLength];
        const randomIndex = Math.floor(Math.random() * wordList.length);
        targetWord = wordList[randomIndex];
        // Show custom word UI in normal mode
        document.getElementById('customWordSection').style.display = 'flex';
    }

    gameState = {
        wordLength: wordLength,
        maxAttempts: 6,
        currentWord: '',
        currentRow: 0,
        currentTile: 0,
        gameOver: false,
        letterStatus: {},
        targetWord: targetWord,
        customWord: isCustom
    };

    console.log('Target word:', gameState.targetWord); // For debugging

    createBoard();
    resetKeyboard();
    document.getElementById('message').textContent = '';
}

function createBoard() {
    const board = document.getElementById('gameBoard');
    board.innerHTML = '';

    for (let i = 0; i < gameState.maxAttempts; i++) {
        const row = document.createElement('div');
        row.className = 'row';
        row.id = `row-${i}`;

        for (let j = 0; j < gameState.wordLength; j++) {
            const tile = document.createElement('div');
            tile.className = 'tile';
            tile.id = `tile-${i}-${j}`;
            row.appendChild(tile);
        }

        board.appendChild(row);
    }
}

function setupEventListeners() {
    // Keyboard click events
    document.querySelectorAll('.key').forEach(key => {
        key.addEventListener('click', () => {
            const letter = key.dataset.key;
            handleInput(letter);
        });
    });

    // Physical keyboard events
    document.addEventListener('keydown', (e) => {
        if (gameState.gameOver) return;

        if (e.key === 'Enter') {
            handleInput('Enter');
        } else if (e.key === 'Backspace') {
            handleInput('Backspace');
        } else if (/^[a-zA-Z]$/.test(e.key)) {
            handleInput(e.key.toUpperCase());
        }
    });

    // New game button
    document.getElementById('newGame').addEventListener('click', initializeGame);

    // Word length selector
    document.getElementById('wordLength').addEventListener('change', initializeGame);
}

function handleInput(key) {
    if (gameState.gameOver) return;

    if (key === 'Enter') {
        submitGuess();
    } else if (key === 'Backspace') {
        deleteLetter();
    } else if (gameState.currentTile < gameState.wordLength) {
        addLetter(key);
    }
}

function addLetter(letter) {
    if (gameState.currentTile < gameState.wordLength) {
        const tile = document.getElementById(`tile-${gameState.currentRow}-${gameState.currentTile}`);
        tile.textContent = letter;
        tile.classList.add('filled');
        gameState.currentWord += letter;
        gameState.currentTile++;
    }
}

function deleteLetter() {
    if (gameState.currentTile > 0) {
        gameState.currentTile--;
        const tile = document.getElementById(`tile-${gameState.currentRow}-${gameState.currentTile}`);
        tile.textContent = '';
        tile.classList.remove('filled');
        gameState.currentWord = gameState.currentWord.slice(0, -1);
    }
}

function submitGuess() {
    if (gameState.currentTile !== gameState.wordLength) {
        showMessage('Not enough letters', 2000);
        return;
    }

    // Check if word is in word list (or is the custom target word)
    const wordList = WORD_LISTS[gameState.wordLength];
    const isValidWord = wordList.includes(gameState.currentWord) ||
                        (gameState.customWord && gameState.currentWord === gameState.targetWord);

    if (!isValidWord) {
        showMessage('Not in word list', 2000);
        shakeTiles();
        return;
    }

    // Check the guess
    checkGuess();

    // Move to next row
    gameState.currentRow++;
    gameState.currentTile = 0;
    gameState.currentWord = '';

    // Check win/loss
    if (gameState.currentRow === gameState.maxAttempts && !gameState.gameOver) {
        gameState.gameOver = true;
        showMessage(`Game Over! The word was ${gameState.targetWord}`, 0);
    }
}

function checkGuess() {
    const guess = gameState.currentWord;
    const target = gameState.targetWord;
    const result = [];
    const targetLetters = target.split('');
    const guessLetters = guess.split('');

    // First pass: mark correct letters
    for (let i = 0; i < gameState.wordLength; i++) {
        if (guessLetters[i] === targetLetters[i]) {
            result[i] = 'correct';
            targetLetters[i] = null;
            guessLetters[i] = null;
        }
    }

    // Second pass: mark present letters
    for (let i = 0; i < gameState.wordLength; i++) {
        if (guessLetters[i] !== null) {
            const index = targetLetters.indexOf(guessLetters[i]);
            if (index !== -1) {
                result[i] = 'present';
                targetLetters[index] = null;
            } else {
                result[i] = 'absent';
            }
        }
    }

    // Apply colors to tiles
    for (let i = 0; i < gameState.wordLength; i++) {
        const tile = document.getElementById(`tile-${gameState.currentRow}-${i}`);
        const letter = guess[i];

        setTimeout(() => {
            tile.classList.add(result[i]);
            updateKeyboard(letter, result[i]);
        }, i * 300);
    }

    // Check if won
    if (result.every(r => r === 'correct')) {
        gameState.gameOver = true;
        setTimeout(() => {
            showMessage('Congratulations! You won!', 0);
        }, gameState.wordLength * 300);
    }
}

function updateKeyboard(letter, status) {
    const key = document.querySelector(`[data-key="${letter}"]`);
    if (!key) return;

    const currentStatus = gameState.letterStatus[letter];

    // Priority: correct > present > absent
    if (currentStatus === 'correct') return;
    if (currentStatus === 'present' && status === 'absent') return;

    gameState.letterStatus[letter] = status;
    key.classList.remove('correct', 'present', 'absent');
    key.classList.add(status);
}

function resetKeyboard() {
    document.querySelectorAll('.key').forEach(key => {
        key.classList.remove('correct', 'present', 'absent');
    });
}

function shakeTiles() {
    const row = document.getElementById(`row-${gameState.currentRow}`);
    row.style.animation = 'shake 0.5s';
    setTimeout(() => {
        row.style.animation = '';
    }, 500);
}

function showMessage(text, duration) {
    const messageEl = document.getElementById('message');
    messageEl.textContent = text;

    if (duration > 0) {
        setTimeout(() => {
            messageEl.textContent = '';
        }, duration);
    }
}

// Setup custom word UI
function setupCustomWordUI() {
    const createChallengeBtn = document.getElementById('createChallenge');
    const customWordInput = document.getElementById('customWordInput');
    const shareLink = document.getElementById('shareLink');
    const copyLinkBtn = document.getElementById('copyLink');

    createChallengeBtn.addEventListener('click', () => {
        const word = customWordInput.value.toUpperCase().trim();

        // Validate word
        if (!word) {
            showMessage('Please enter a word', 2000);
            return;
        }

        if (!/^[A-Z]+$/.test(word)) {
            showMessage('Only letters allowed', 2000);
            return;
        }

        if (word.length < 4 || word.length > 8) {
            showMessage('Word must be 4-8 letters', 2000);
            return;
        }

        // Generate shareable link
        const encoded = encodeWord(word);
        const baseUrl = window.location.origin + window.location.pathname;
        const shareUrl = `${baseUrl}?w=${encoded}`;

        shareLink.value = shareUrl;
        shareLink.style.display = 'block';
        copyLinkBtn.style.display = 'inline-block';

        showMessage('Challenge link created!', 2000);
    });

    copyLinkBtn.addEventListener('click', () => {
        shareLink.select();
        shareLink.setSelectionRange(0, 99999); // For mobile devices

        navigator.clipboard.writeText(shareLink.value).then(() => {
            showMessage('Link copied to clipboard!', 2000);
        }).catch(() => {
            showMessage('Failed to copy link', 2000);
        });
    });

    // Clear input on Enter
    customWordInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') {
            createChallengeBtn.click();
        }
    });
}

// Add shake animation CSS via JavaScript
const style = document.createElement('style');
style.textContent = `
    @keyframes shake {
        0%, 100% { transform: translateX(0); }
        10%, 30%, 50%, 70%, 90% { transform: translateX(-5px); }
        20%, 40%, 60%, 80% { transform: translateX(5px); }
    }
`;
document.head.appendChild(style);
